#docker compose -f ./docker/docker-compose.coder.yml up
#docker compose -f ./docker/docker-compose.coder.yml down -v --remove-orphans
version: '3.7'

services:
    redis:
        image: redis:latest
        restart: always
        command:
            - /bin/sh
            - -c
            - redis-server --save 20 1 --loglevel warning --requirepass "$${REDIS_ROOT_PASSWORD:?REDIS_ROOT_PASSWORD variable is not set}"
        volumes:
            - type: bind
              source: ./cache
              target: /data
        env_file:
            - '.env'
        networks:
            - backend
        ports:
            - 6379:6379

networks:
    backend:
